Algoritmo "Exercicio 1"
// Descrição   : escrever na tela numeros de dois extremos determinados pelo usuário
// Autor(a)    : Thifany Garcia
// Data atual  : 06/09/2022
Var
num1,num2,cont:inteiro


Inicio
// entrada
escreval ("De qual número você quer começar a contar?")
leia(num1)
escreval ("Até qual número você quer contar?")
leia(num2)

para cont de num1 ate num2 faca
     escreval (cont)
fimpara



Fimalgoritmo