Algoritmo "parouimpar"
// Descrição   : verificar se um numero é par ou impar
// Autor(a)    : Thifany Garcia
// Data atual  : 26/07/2022
Var
numero:inteiro


Inicio
//entrada
escreval ("Olá, vamos verificar para você se um número é par ou ímpar")
escreval ("Digite um número: ")
leia(numero)

//processamento
se (numero mod 2 = 0) entao
   escreval ("este número é par")
senao
   escreval ("este número é ímpar")
fimse


Fimalgoritmo