Algoritmo "Exercício 2"
// Descrição   : Descrever uma multiplicação
// Autor(a)    : Thifany Garcia
// Data atual  : 06/09/2022
Var
numero,acu,mult:inteiro


Inicio
//entrada
escreval ("De qual número você quer calcular a tabuada?")
leia(numero)

//processamento
acu<-0
repita
      mult<-(numero*acu)
      escreval (numero,"x",acu,"=",mult)
      acu<-acu+1
ate acu=10







Fimalgoritmo
