algoritmo "calculopeca"
// Função : solicitar o valor da peça, quantidade comprada e informar o total da compra
// Autor : Thifany Garcia
// Data : 26/04/2022
var
valor,qtde,total:real

inicio
//entrada
escreval ("Digite a quantidade de peças compradas:")
leia(qtde)

escreval ("Digite o valor unitário de cada peça")
leia(valor)

//processamento
total<-valor*qtde

//saida
limpatela
escreval ("O valor total de sua compra é:", total)




fimalgoritmo
