algoritmo "conversaodolar"
// Função : Converter reais em dólar
// Autor : Thifany Garcia
// Data : 26/04/2022

var
conv,reais,cotdol:real

inicio
//entrada
escreval ("Digite a cotação do dólar atual:")
leia (cotdol)

escreval ("Escreva o valor que você quer converter para dólar")
leia (reais)

//processamento
conv<-reais/cotdol

//saida
escreval("O resultado da conversão é:", conv)





fimalgoritmo
